USE DataIngestion493286;

-- ALTER TABLE LAUREATI_CLASSE_VOTO DROP FOREIGN KEY laureati_classe_voto_ibfk_1;
DROP TABLE IF EXISTS ATENEI;
DROP TABLE IF EXISTS LAUREATI_CLASSE_VOTO;

CREATE TABLE ATENEI(
COD_ATENEO SMALLINT PRIMARY KEY,
NOME_ESTESO VARCHAR(100),
NOME_OPERATIVO VARCHAR(60),
STATO CHAR(10),
TIPOLOGIA VARCHAR(50),
STATALE_LIBERA CHAR(12),
VIA VARCHAR(100),
COMUNE VARCHAR(30),
PROVINCIA VARCHAR(30),
REGIONE VARCHAR(50),
AREA_GEOGRAFICA CHAR(10),
URL VARCHAR(100),
ATENEO_DIMENSIONE VARCHAR(50)
);

CREATE TABLE LAUREATI_CLASSE_VOTO(
ANNO YEAR,
ATENEO_COD SMALLINT,
ATENEO_NOME VARCHAR(100),
ATENEO_REGIONE VARCHAR(50),
ATENEO_AREAGEO CHAR(10),
CLASSE_VOTO_LAUREA CHAR(20),
GENERE CHAR(1),
NUMERO_LAUREATI SMALLINT,
PRIMARY KEY(ANNO, ATENEO_COD, CLASSE_VOTO_LAUREA, GENERE),
FOREIGN KEY(ATENEO_COD) REFERENCES ATENEI(COD_ATENEO) ON UPDATE CASCADE
);


select * 
from laureati_classe_voto
where ATENEO_REGIONE = 'ITALIA';
-- HA ELIMINATO LE TUPLE RIASSUNTIVE PER ANNO DURANTE LA IMPORT DA CSV








